#!/usr/bin/env python
# -*- coding: utf-8 -*-
class Calc:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def add(self):
        return self.a+self.b
    def sub(self):
        return self.a-self.b
    def mul(self):
        return self.a* self.b
    def div(self):
        if self.b!=0:
            return self.a/self.b
        else:
            return  "相除操作中，除数不能为0"
if __name__=='__main__':
    a=input('请输入第1个数a:')
    b=input('请输入第2个数b:')
    c=Calc(a,b)
    print (c.add())
    print (c.sub())
    print (c.mul())
    print(c.div())
