#!/usr/bin/env python
# -*- coding: utf-8 -*-
import random
class MySort:
    #初始化
    def init(self,start,end,count):
        self.start=start
        self.end=end
        self.count=count
        self.radom_a=[]
    def ran(self):
        [random.randit(self.start,self.end ) for in range(count)]
        ms=ran(self)
        print ms
    def mysort(self):
        for i 

if __name__ =='__main__':
    sort_data=Mysort(10,1000,100)

    print (sorted_data)
